### ISSUE TITLE
Cluster dialog can deadlock cyctoscape UI

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#108]
There is a dialog that asks "would you like to cluster anyways?", if this pops up when there is already a task dialog showing then the two dialogs block each other and they never go away. The only thing to do is kill cytoscape.

Steps to reproduce:
Open a large enrichment map.
Press Ctrl-A to select all nodes.

**Comment by risserlin** [comment]
This is a recurring issue that has been fixed before.  I haven't had this issue in a while.  Try select the whole network manually with the click and drag.  If it occurs there then something has been broken because I have used it with large networks for the past few months and haven't had this issue.  

I do not use ctrl A to select the network.  If it doesn't occur when you manually select the whole network then it is something specific to the ctrl A.  

I also use the filters with no problems (i.e. no race condition).

**Comment by mikekucera** [comment]
This is still a problem.

**Comment by mikekucera** [comment]
After talking to Christian it turns out that the old code was actually the proper way to do it (tunables in a task). That should work so the bug is actually in cytoscape.

So I'm going to revert commit c302be3 and take this bug off the 2.1 milestone.

**Comment by mikekucera** [comment]
Not exactly sure what happened but I didn't properly commit the fix.
