### ISSUE TITLE
edge witdth/ post-analysis

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#121]
I lost the edge width when I reopened a stored session (all pink edges look like thin lines). For the correct width to reappear, I do: menu bar -->Apps  -->  EnrichmentMap --> Post-analysis edge width and click on OK  . 

Thanks,
Veronique

**Comment by mikekucera** [comment]
Turns out that using an Equation to calculate the edge widths was a bad idea. The equations are calculated during session restore before the network manager is set up. So the information needed to calculate the widths is not available yet. But when you go look at the table browser the values look correct because the table browser recalculates them. That's why I didn't realize at first the problem was with the equation itself.

I rewrote it to just calculate all the edge widths when the post-analysis visual style is created and store the results in the column. I removed the dependency on equations-api.
