### ISSUE TITLE
David test failure

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#133]
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.04 sec <<< FAILURE! - in org.baderlab.csplugins.enrichmentmap.task.LoadDavidResultTest
testLoad2DavidResult_withoutexpression(org.baderlab.csplugins.enrichmentmap.task.LoadDavidResultTest)  Time elapsed: 0.025 sec  <<< FAILURE!
java.lang.AssertionError: expected:<114> but was:<84>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at org.baderlab.csplugins.enrichmentmap.task.LoadDavidResultTest.testLoad2DavidResult_withoutexpression(LoadDavidResultTest.java:155)

**Comment by mikekucera** [comment]
The bug is in EnrichmentMap.getAllGenesets(). 
If both datasets contain the same geneset then its basically random which one it returns. (Iteration order over a HashMap is not specified.)

Sometimes it returns the "ACETYLATION" geneset from dataset2 and the test passes. But if it returns the one from dataset1 it will fail.

What should be the correct behaviour when a geneset with the same name is in both datasets and the geneset has different contents in each dataset?

This bug has me a bit nervous because getAllGenesets() is called in a few places.

**Comment by risserlin** [comment]
The original design of EM the assumption was that we would only ever have one gmt (geneset definition file) but when we introduced comparison between different data type and different species that changed this.  

getallGenesets gets all the genesets from all of the datasets.  The call in David test should be specific to the dataset as opposed to getting all the genesets from the enrichment map. 
dataset2..getSetofgenesets().getGenesets()
instead of getAllGenesets()

**Comment by mikekucera** [comment]
I fixed the specific problem with the test case.
