### ISSUE TITLE
Enrichment map with 2 datasets (along with expression values)

### ISSUE THREAD

**Issue by Indhupriya-s** [BaderLab/EnrichmentMapApp#139]
I had uploaded 2 datasets (DAVID results) along with their respective expression datasets (in text formats). Enrichment map is generated, but for a few GO terms I am unable to see the Heat Map (nodes and edges) even though the terms and corresponding gene expression values are present in all input files
![enrichmentmap_issue](https://cloud.githubusercontent.com/assets/16202366/11648985/b39b2df0-9d9f-11e5-8a86-d5340a388e92.png)
.

**Comment by risserlin** [comment]
What version of EM are you using?  If you are using 2.0.1 (that is available in the app store) please upgrade to development version that can be found here: http://baderlab.org/Software/EnrichmentMap#Development_Versions

I believe this was a bug that was fixed in the latest version. You will need to recreate the Enrichment map with the development version.

**Comment by Indhupriya-s** [comment]
Hi,

I tried installing the developer version but I do not get the menu option of EnrichmentMap to create a new map.

Please let me know how else I can address this problem.

Thanks.

**Comment by risserlin** [comment]
The development version only works in cytoscape 3.2.1 or higher. What version of cytoscape are you using?

**Comment by Indhupriya-s** [comment]
Yeah, I realized that and I was able to install the development version. It is working fine. This version shows all the heat maps.

Thanks.
