### ISSUE TITLE
class definition don't reload on session restore

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#144]
If a network is created using a class file and in the original session you are able to see the two colors delineating the classes in the expression viewer.  Save session and then re-open the session and the class labelling is gone. 

before save:
![image](https://cloud.githubusercontent.com/assets/3842763/12430709/128b2fd2-bebf-11e5-9153-8ba9b17de21b.png)

After save:
![image](https://cloud.githubusercontent.com/assets/3842763/12430719/1c3fd73a-bebf-11e5-8d4e-07b7b5533d37.png)

**Comment by mikekucera** [comment]
Fixed in the 2.2 branch. The classes were not being saved to the session properly so this won't fix existing session files. New session files saved with 2.2 will work.

I'm not going to cherry-pick the fix to the develop branch because we will be reworking the session saving and the heat map, so I don't think the exact fix in commit e5fbfb0 will apply. I will keep this issue open so that we don't forget about it.

**Comment by mikekucera** [comment]
Verified this works in EM3
