### ISSUE TITLE
Cannot display the name of gene set

### ISSUE THREAD

**Issue by crysrain** [BaderLab/EnrichmentMapApp#162]
![image](https://cloud.githubusercontent.com/assets/8159227/18501734/2806ac00-7a18-11e6-9434-dab46f4c319c.png)

Is there anything with DAVID output file?

Best,

Jian

**Comment by risserlin** [comment]
We recently changed the enrichment map visual style to by default to show the geneset description instead of the geneset name.  For David results this is meaningless.  So once you have created your network you just have to update your network style to map the label to the Geneset name.  David only recently got updated so we haven't been using it but we will also fix this issue in the next enrichment map release.  (#159) 
![screen shot 2016-07-18 at 11 47 08 am](https://cloud.githubusercontent.com/assets/3842763/18513688/877d8a84-7a5c-11e6-9b92-379ca9093e55.png)
