### ISSUE TITLE
What constitutes a new dataset when running post analysis?

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#203]
When i run post analysis once with "Mann_whitney_less" a new dataset is created with either a default name or the name that I have given it the first time a new dataset appears in the EM panel

If I then run post analysis with a new name and "MANN_WHITNEY_GREATER" no new data appears but the edges associated with the analysis do.

**Comment by mikekucera** [comment]
In EM 2 there is no separate dataset for PA. When you run PA you choose an existing dataset and the signature genesets are added to that dataset. If you run PA a second time it essentially overlays the second run on top of the first. PA edges from the first run are simply updated, new edges may be added, and if there are existing edges that no longer pass the cutoff then the user is prompted if they want to keep them or delete them.

In EM 3 we run PA in "batch" against all the data sets. Then we create a separate data set just for PA to store the signature gene sets. Now when PA is run a second time what should happen?
1) Do something similar to EM 2 by overlaying the second run on top of the existing PA dataset?
2) Create a new dataset with all new edges, don't modify the existing PA dataset at all.

Right now its doing 1, because that's most similar to EM 2 and the existing code works that way. However, I think it would be relatively easy to change the behaviour to 2. I think that's probably what you want right?

**Comment by risserlin** [comment]
Do you have to run pa in batch?  If the user had 10 datasets but they are only interested in a particular post analysis for one of those datasets then they would run it in batch and have to manually delete for the 9 other datasets?  Batch is definitely useful but I can see a use case for both scenarios.

I like option 2 better.  One question though, if the first run of PA and second run of PA have the same node (or edge) in them will the node be duplicated? or will there just be the one?  If you delete one of the PA datasets will the node remain?

**Comment by veroniquevoisin** [comment]
not sure as I haven't tested it and not sure to fully understand, I would say 1 for now. : should update PA (past PA edges can be deleted), same as current.  yes , would be good to be able to slect the dataset on which we want to do PA, batch analysis on all datasets should be an advanced option.

**Comment by mikekucera** [comment]
@risserlin If we go with option 2 then It will work the same way nodes/edges work in the base EM network. A node is created if the gene set passes the cutoff in at least one dataset. An edge (assuming you are using distinct edges) is created for each separate dataset. If you run PA multiple times it will not add new nodes if the signature gene set already exists in the network, but it will add new edges every time because its a separate data set. Keep in mind with the new control panel you can hide or delete PA datasets at any time.

**Comment by mikekucera** [comment]
No problem to make "batch mode" optional, I'll open a separate issue for that.

**Comment by mikekucera** [comment]
I have implemented option 2. I will send out a new beta build soon. I can always revert the change if needed. I'm closing this issue but if there are any additional problems it can be reopened.
