### ISSUE TITLE
Moving the number of edges sliders does not update parameters in advanced pane

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#213]
moving the slider that specifies number of edges (sparse to dense) if after moving the slider you click on advanced options to see what the values are for similarity metric and cut-off it is the same (overlap cutoff = 0.5) no matter where the slider is.
<img width="490" alt="screen shot 2017-06-16 at 11 52 04 am" src="https://user-images.githubusercontent.com/3842763/27234303-87eb8190-528a-11e7-856f-772c687419ee.png">
<img width="449" alt="screen shot 2017-06-16 at 11 52 15 am" src="https://user-images.githubusercontent.com/3842763/27234306-8994fd6e-528a-11e7-8fa0-228dee75e0c6.png">

**Comment by mikekucera** [comment]
Interesting. I didn't think to make them related but yes it makes sense.

**Comment by mikekucera** [comment]
The default for the advanced options is Overlap:0.5, which corresponds to the 4th tick on the slider, so I'm going to make that the default for the slider so they are consistent. 

Also its not possible to synchronize in the opposite direction because on the advanced panel you can enter values that don't correspond to a slider tick.

**Comment by risserlin** [comment]
Can you make the default the centre tick mark Combined 0.375 instead?

**Comment by mikekucera** [comment]
no problem

**Comment by mikekucera** [comment]
Just ran into an issue. EM has properties (Edit > Preferences > Properties) to adjust the default cutoff values for the different metrics. But we redefined those values for the slider. So now I can add more properties so that all the ticks on the slider can be adjusted, or I can just hard code all the values and remove the properties. Ruth, do you have a need to adjust the values used by the slider using properties?

**Comment by risserlin** [comment]
Not sure if I understand the question.  What are the additional properties?

**Comment by mikekucera** [comment]
On the advanced tab there are 3 choices in the combo box (overlap, jaccard, combined) and each has a default cutoff value that can be set via a property. The slider has 5 ticks, each has a metric and a cutoff value. The values for the slider ticks are hard coded right now.

Now that the slider is synchronized with the advanced panel it basically overwrites the values that came from the properties. So now the properties have no effect. I can fix it by adding properties for the slider ticks, essentially making the slider customizable, or I can scrap the whole thing, remove the properties and just leave the slider values hard coded.

**Comment by mikekucera** [comment]
I'm going to hard code the values. There are too many corner cases and potential problems with allowing the ticks to be customized while still synchronizing to the advanced panel. It makes the code more complex.
