### ISSUE TITLE
How to remove labels from nodes?

### ISSUE THREAD

**Issue by crysrain** [BaderLab/EnrichmentMapApp#24]
Hi,

I am learning to make my Enrichment Map. How can I remove the individual GO number and annotation from nodes?

Thanks.

**Comment by risserlin** [comment]
What version of enrichment map are you using?  Do you want to remove all nodes and labels to make a figure or do you want to delete a single label?

**Comment by crysrain** [comment]
Hi,

I am using Enrichment Map v2.0. I am trying to make a map similar to "Enrichment Map: A Network-Based Method for Gene-Set Enrichment Visualization and Interpretation" Figure 7. 
![image](https://cloud.githubusercontent.com/assets/8159227/3572839/b073a3e0-0b6b-11e4-977c-0521bb708c60.png)

I want to remove all labels. Can I delete anyone I don't want?

Thanks.

**Comment by risserlin** [comment]
In previous versions of cytoscape you could simply set the label font size to zero and export the network and then reset the font size to whatever you wanted if you wanted to see the node names again.
In cytoscape3 you can in the control Panel -> style
Right click on Label -> Edit -> Remove Mappings from selected Visual Properties
Export network 

If you want to re add the label 
Click on label to expand
Set Colum to EM#_formatted_name
Set Mapping Type to Passthrough Mapping

**Comment by crysrain** [comment]
Hi Isserlin,

I removed the labels. 
Thank you very much.
I have another question. The DNA Metabolism set is separated from Cell Cycle set in Figure 3. How did you make it connected with Cell Cycle and Transcription in Figure 5?

**Comment by risserlin** [comment]
Figure3 and figure 5 are different analyses.  Figure 3 is only the 24hr time point where as figure 5 is a two dataset map with both 12hr and 24hr.  They are connected in figure 5 because of genesets that are only found to be enriched at the 12hr time point.

**Comment by crysrain** [comment]
Hi Isserlin,

I am sorry I have so many questions. 
Why did you get rid of " terms annotating more than 500 or less than 10 genes"? 
Which software did you use to manually circle and label to highlight prevalent biological functions?
Thanks.

**Comment by risserlin** [comment]
those are common thresholds although I generally use less than 5 instead of less than 10.  With huge or small geneset it is more likely that the significance is a result of chance so people generally fiter them out.
Annotation for those figures was done manually in power point or illustrator.  We are currently working on that feature so that it can be done directly from within cytoscape.  Prototype should be available soon if you want to try it out for us.

**Comment by crysrain** [comment]
Hi,
Thanks. 
I generated Heat Map (Nodes) in Cytoscape 3.1.1 EM2.0. When I used "Export Expression Set (PDF)" to export the Heat Map, nothing happened. Then I tried Cytoscape 2.8.3 and EM1.3. In this situation, I can export Heat map as PDF file. However, the heat map just showed up-regulated genes data. I also tried Cytoscape 3.0.0 and 3.0.2. It shows that EM 2.0 is installed. But from App item I can not find EM. So what combination of Cytoscape and EM I can use to  export Heat Map image?
Thanks.

Jian

**Comment by risserlin** [comment]
Hi Jian, 
I saw your post from yesterday.  I flagged it as a bug.  The export heatmap function for cytoscape 3.1 has a bug that I am currently working on fixing.  Em 2.0 is only compatible with cytoscape 3.1 (it doesn't work in 3.0).
It should work in cytoscape 2.8 with EM 1.3.  We were never able to perfect the pdf export because of issues with pdf exporter library.  The headers always came up at the bottom of the pdf instead of at the top.  We usually took scrren shots of the heatmap for figures.  
Thanks, 
Ruth

**Comment by crysrain** [comment]
Hi Ruth,

Thank you very much. I know what I can do now. Could you please let know when you fix the bug?

Best,

Jian

----- 原始邮件 -----
发件人: "Ruth Isserlin" notifications@github.com
收件人: "BaderLab/EnrichmentMapApp" EnrichmentMapApp@noreply.github.com
抄送: "crysrain" huang2@uwm.edu
发送时间: 星期三, 2014年 7 月 23日 下午 3:26:20
主题: Re: [EnrichmentMapApp] How to remove labels from nodes? (#24)

Hi Jian, 
I saw your post from yesterday. I flagged it as a bug. The export heatmap function for cytoscape 3.1 has a bug that I am currently working on fixing. Em 2.0 is only compatible with cytoscape 3.1 (it doesn't work in 3.0). 
It should work in cytoscape 2.8 with EM 1.3. We were never able to perfect the pdf export because of issues with pdf exporter library. The headers always came up at the bottom of the pdf instead of at the top. We usually took scrren shots of the heatmap for figures. 

Thanks, 
Ruth

**Comment by mikekucera** [comment]
Sorry the discussion is quite long, what exactly is the bug here? The heatmap not exporting correctly? When I click the export button I get a dialog that says "PDF export currently not available".

**Comment by risserlin** [comment]
This can be forked into two separate issues.
One is related to issue #134  - he wants an easy way to export the network without labels.
The second is PDF export which is currently unsupported in the latest version of EM.  You mentioned there might be something in cytoscape that we could use instead of the non-osgi library that we were using in the previous version.
