### ISSUE TITLE
gprofiler results with two phenotypes is not visualized correctly

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#269]
Using 3.0 released version of EM.

running gprofiler with 2 different phenotypes is not represented in map:
![screen shot 2017-09-06 at 2 48 31 pm](https://user-images.githubusercontent.com/3842763/30128982-7ea49bbc-9312-11e7-871e-625be8152eb2.png)

If you change the visualization to NES (not technically relevant for gprofiler results) you see the correct phenotype info:
![screen shot 2017-09-06 at 2 49 44 pm](https://user-images.githubusercontent.com/3842763/30129047-a5dbafae-9312-11e7-9f88-40d2291efe2a.png)

**Comment by mikekucera** [comment]
The phenotype info from the gprofiler enrichment file is currently stored in the NES column (not sure why), that's why your workaround works.

I could create a new column to store the phenotype and create a new chart visualization just for gprofiler phenotype. Would that work for you?

**Comment by risserlin** [comment]
How does the color by dataset work for GSEA?  Is it using the NES column?

When you say that gprofiler phenotypes are stored in the NES, are positive phenotypes given NES of 1 and negative phenotypes given a NES of -1?

**Comment by mikekucera** [comment]
No, color by dataset does not use the NES column. I had to create a new
column to store a list of the datasets that each node belongs to.

Yes, but you have to set the phenotypes correctly in the creation dialog,
otherwise it just sets the value of the NES column to the phenotype value.
(Are gprofiler phenotypes always numbers?).

Here is the code...
https://github.com/BaderLab/EnrichmentMapApp/blob/develop/EnrichmentMapPlugin/src/main/java/org/baderlab/csplugins/enrichmentmap/parsers/ParseGenericEnrichmentResults.java#L116-L129

**Comment by risserlin** [comment]
Ruth: When you say that gprofiler phenotypes are stored in the NES, are positive phenotypes given NES of 1 and negative phenotypes given a NES of -1?

Mike: Yes, but you have to set the phenotypes correctly in the creation dialog,
otherwise it just sets the value of the NES column to the phenotype value.
(Are gprofiler phenotypes always numbers?).

Ok.  I just looked at the code.  This is a feature that is not documented anywhere.  Originally the generic file format only recognized two phenotypes (1 and -1) and there was no connection to specified phenotypes (http://baderlab.org/Software/EnrichmentMap/UserManual#Generic_results_files) which is probably why the gprofiler two classes file is not working.  
For backwards compatibility we need to make sure the original generic file works.  

With regards to your questions "Mike:I could create a new column to store the phenotype and create a new chart visualization just for gprofiler phenotype. Would that work for you?"  
Why does it have to be a special chart visualization just for gProfiler?  Can't it just use the same mechanism as other data types?

**Comment by mikekucera** [comment]
If you are ok using the existing NES chart then there's not much to be done here. The code I linked to has not been changed in a very long time so the data import is backwards compatible. 

I could make it so that the two phenotype gprofiler case is identified and the NES chart is automatically chosen as the default. I could also change the name of the NES chart to "phenotypes" so that the user isn't confused.
