### ISSUE TITLE
Change attribute names so they are consistent between different EMs

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#272]
currently EM attributes get a special prefix depending on which number enrichment map it is in the cytoscape session.  (originally was done to accommodate multiple EMs in a session in cytoscape 2.X.)  I am not sure if it is still required but if it isn't it would be very helpful to change it to be consistent between networks.  When writing work flow using cyrest it would be easier to be able to use the same attribute for each subsequent network as opposed to having to figure out what the attribute name is in the current network.

**Comment by mikekucera** [comment]
Hi Ruth,

Cytoscape 3.7 has a new feature called column namespaces. If a column name has the format "Namespace::Name" then it gets displayed nicer in the table browser. I'd like to take advantage of this and change our column names to use "EnrichmentMap::" instead of "EM1_", "EM2_"...

It looks like this in the table browser:

<img width="885" alt="screen shot 2018-11-21 at 11 08 17 am" src="https://user-images.githubusercontent.com/5350528/48853573-cb29a880-ed7d-11e8-9436-0e7372fcadc8.png">

Your scripts will have to be changed to use the new prefix. Old session files will be unaffected.

Do you have any objections to this change?

Thanks.

**Comment by risserlin** [comment]
When I search for specific columns I grep to the column name minus the network specific tag (for example "GS_descr") so change is fine with me.
