### ISSUE TITLE
The enrichment map is not automatically generated after a Enrichment map run in GSEA

### ISSUE THREAD

**Issue by pharaveej** [BaderLab/EnrichmentMapApp#30]
Enrichment Map v2.0 Build:400
Cytoscape 3.1.1
Windows7

After I completes my GSEA run, I clicked on Enrichment Map Visualization, set all parameters and clicked Build Enrichmant Map, then Cytoscape was launched but nothing was shown on the Cytoscape. I just got a black screen. Then I tried it the old way by Apps > Enrichment Map > Create Enrichment Map > choose GSEA, in Expression box, choose the .rpt file of the GSEA result > Build. And I got this warning:

![warning](https://cloud.githubusercontent.com/assets/8388961/3894027/4351b39c-2240-11e4-8504-361e05002619.JPG)

What is this warning telling me? What did I do wrong?

Thanks so much in advance for you your help.

**Comment by risserlin** [comment]
Can you expand the window at all to see the rest of the message?

With regards to GSEA and launching cytoscape directly it only works for cytoscape 2.8 and not not 3.X.  It shouldn't even be launching anything above 3  Which version of GSEA is it?

**Comment by pharaveej** [comment]
Hi Ruth.

It’s GSEA v2.1.0 Java Desktop Application. 

I got it now!  Stupid me, I didn’t know that the dialogue can be expand. Now I see that the problem is that the program cannot find the source files for Enrichments1,2, Ranks . The name automatically added in those boxes are not matching with the file name even though I didn’t rename any of the files. 

The generated file path was :          C:\Users\ gsea_home\output\aug12\mouse_SRvsSS_c2Kegg.Gsea.1407858737185\gsea_report_for_SR_1407858737185.xls

But the correct path would be:       C:\Users\gsea_home\output\aug12\mouse_SRvsSS_c2Kegg.Gsea.1407858737185\gsea_report_for_4_1407858737185.xls

‘SR’ is the phenotype which is represented by ‘4’ in the .cls

As I hadn’t changed or renamed the files in any ways, maybe you want to look into this matter.

Best,

Pharavee

**Comment by risserlin** [comment]
Two different issues here I think.  
Did you have cytoscape installed before trying to launch it from GSEA?  Do you have cytoscape 2.8 installed?
Does the above file show up as red in the EM input window?  Any of the other files show up as red?

**Comment by jgarces02** [comment]
Hi, 

I have a similar problem, but in this case I think it's related with the proxy (but I haven't found anything to change the proxy/port)... any idea, please? Thanks in advance!

![image](https://user-images.githubusercontent.com/27858969/30434196-ea8338fc-9966-11e7-8df4-53f7ca56fcfb.png)

**Comment by risserlin** [comment]
Hi, 
Is this the error message that you are getting from GSEA?

**Comment by jgarces02** [comment]
Yes, from the left bottom corner...

[image: Imágenes integradas 1]

**Comment by risserlin** [comment]
Is Cytoscape open with enrichment map installed.  The image didn't come through above but I am assuming you are using the GSEA EM interface.  
Also, in GSEA at the bottom left hand there is a + that might have more info regarding your issue.  Can you send me a screenshot of that.

**Comment by jgarces02** [comment]
Dear Ruth,

Yes, Cystoscape is open when I try to launch the Enrichment Map option
(however, GSEA opens it again automatically).

Yes again, I'm using the UI GSEA and the code pasted in the first question
(I copy again below) is the error message that appears in this + bottom
left. I can't attach a screenshot of the entire message because the image
is not big enough, sorry.

Here, the code:

*Done initing things while splashing*
*INFO - C:\Program Files\Cytoscape_v3.5.1*
*INFO - Latest version of cytoscape is:Cytoscape_v3.5.1*
*INFO - looking for prefix plugin:enrichmentmap*
*INFO - EM version installed:-1.0*
*java.io.IOException: Invalid signature file digest for Manifest main
attributes*
*INFO - command issued:cmd /c start cytoscape.bat -R 1234*
*to parse>gseaftp.broadinstitute.org
<http://gseaftp.broadinstitute.org>://pub/gsea/annotations/HuGene_2_0_st.chip<
got: [gseaftp.broadinstitute.org
<http://gseaftp.broadinstitute.org>://pub/gsea/annotations/HuGene_2_0_st.chip]*
*INFO - Begun importing: Dataset from: selMOvsSP_ALL_P01.gct*
*INFO - File download started.  Retrieving HuGene_2_0_st.chip from remote
server...*
*INFO - Download complete*
*INFO - Begun importing: Chip from: ftp://gseaftp.broadinstitute.org
<http://gseaftp.broadinstitute.org>://pub/gsea/annotations/HuGene_2_0_st.chip*
*INFO - Parsed from dotchip : 51899*
*INFO - File found in local file cache; will process
C:\Users\jgarces\gsea_home\file_cache\chip\GENE_SYMBOL.chip in place of
ftp://gseaftp.broadinstitute.org/pub/gsea/annotations/GENE_SYMBOL.chip
<ftp://gseaftp.broadinstitute.org/pub/gsea/annotations/GENE_SYMBOL.chip>.
Ignore any following message(s) about this URL.*
*INFO - Begun importing: Chip from:
ftp://gseaftp.broadinstitute.org/pub/gsea/annotations/GENE_SYMBOL.chip
<ftp://gseaftp.broadinstitute.org/pub/gsea/annotations/GENE_SYMBOL.chip>*
*INFO - Parsed from unigene / gene symbol: 38870*
*ERROR - No Probe called: GPATCH4 on this chip (chip name is >GENE_SYMBOL<)*
*ERROR - Turning off subsequent error notifications*
*Time taken: 6 secs*
*INFO - successfully connected to cytoscape rest*
*INFO - successfully connected to cytoscape rest*
*INFO - Found enrichment map command*
*INFO - Get
URL:http://localhost:1234/v1/commands/enrichmentmap/gseabuild?edbdir=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.Gsea.1505386424080%5Cedb&pvalue=0.005&qvalue=0.1&overlap=0.5&similaritymetric=OVERLAP&combinedconstant=0.5&expressionfile=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.CollapseDataset.1505402391117%5CselMOvsSP_ALL_P01_collapsed_to_symbols.gct
<http://localhost:1234/v1/commands/enrichmentmap/gseabuild?edbdir=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.Gsea.1505386424080%5Cedb&pvalue=0.005&qvalue=0.1&overlap=0.5&similaritymetric=OVERLAP&combinedconstant=0.5&expressionfile=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.CollapseDataset.1505402391117%5CselMOvsSP_ALL_P01_collapsed_to_symbols.gct>*
*DEBUG - CookieSpec selected: default*
*DEBUG - Auth cache not set in the context*
*DEBUG - Connection request: [route: {}->http://localhost:1234][total kept
alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]*
*DEBUG - Connection leased: [id: 0][route: {}->http://localhost:1234][total
kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]*
*DEBUG - Opening connection {}->http://localhost:1234
<http://localhost:1234>*
*DEBUG - Connecting to localhost/127.0.0.1:1234 <http://127.0.0.1:1234>*
*DEBUG - Connection established 127.0.0.1:65387
<http://127.0.0.1:65387><->127.0.0.1:1234 <http://127.0.0.1:1234>*
*DEBUG - Executing request GET
/v1/commands/enrichmentmap/gseabuild?edbdir=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.Gsea.1505386424080%5Cedb&pvalue=0.005&qvalue=0.1&overlap=0.5&similaritymetric=OVERLAP&combinedconstant=0.5&expressionfile=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.CollapseDataset.1505402391117%5CselMOvsSP_ALL_P01_collapsed_to_symbols.gct
HTTP/1.1*
*DEBUG - Target auth state: UNCHALLENGED*
*DEBUG - Proxy auth state: UNCHALLENGED*
*DEBUG - http-outgoing-0 >> GET
/v1/commands/enrichmentmap/gseabuild?edbdir=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.Gsea.1505386424080%5Cedb&pvalue=0.005&qvalue=0.1&overlap=0.5&similaritymetric=OVERLAP&combinedconstant=0.5&expressionfile=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.CollapseDataset.1505402391117%5CselMOvsSP_ALL_P01_collapsed_to_symbols.gct
HTTP/1.1*
*DEBUG - http-outgoing-0 >> Host: localhost:1234*
*DEBUG - http-outgoing-0 >> Connection: Keep-Alive*
*DEBUG - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.2
(Java/1.8.0_144)*
*DEBUG - http-outgoing-0 >> Accept-Encoding: gzip,deflate*
*DEBUG - http-outgoing-0 >> "GET
/v1/commands/enrichmentmap/gseabuild?edbdir=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.Gsea.1505386424080%5Cedb&pvalue=0.005&qvalue=0.1&overlap=0.5&similaritymetric=OVERLAP&combinedconstant=0.5&expressionfile=C%3A%5CUsers%5Cjgarces%5CGoogle+Drive%5CProyectos%5CGEM%5CBiopsia+l%C3%ADquida%5CCzechVSPamplona%5CGSEA_analysis%5Ctest1_MOvsCTC_default_C2cp.CollapseDataset.1505402391117%5CselMOvsSP_ALL_P01_collapsed_to_symbols.gct
HTTP/1.1[\r][\n]"*
*DEBUG - http-outgoing-0 >> "Host: localhost:1234[\r][\n]"*
*DEBUG - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"*
*DEBUG - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.2
(Java/1.8.0_144)[\r][\n]"*
*DEBUG - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"*
*DEBUG - http-outgoing-0 >> "[\r][\n]"*
*DEBUG - http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"*
*DEBUG - http-outgoing-0 << "Access-Control-Allow-Origin: *[\r][\n]"*
*DEBUG - http-outgoing-0 << "Access-Control-Allow-Headers: origin,
content-type, accept, authorization[\r][\n]"*
*DEBUG - http-outgoing-0 << "Access-Control-Allow-Credentials:
true[\r][\n]"*
*DEBUG - http-outgoing-0 << "Access-Control-Allow-Methods: GET, POST, PUT,
DELETE, OPTIONS, HEAD[\r][\n]"*
*DEBUG - http-outgoing-0 << "Content-Type: text/plain[\r][\n]"*
*DEBUG - http-outgoing-0 << "Date: Thu, 14 Sep 2017 15:20:01 GMT[\r][\n]"*
*DEBUG - http-outgoing-0 << "Connection: close[\r][\n]"*
*DEBUG - http-outgoing-0 << "Content-Length: 98[\r][\n]"*
*DEBUG - http-outgoing-0 << "[\r][\n]"*
*DEBUG - http-outgoing-0 << "Failed: None of the gene sets have passed the
filter. Try relaxing the gene set filter parameters."*
*DEBUG - http-outgoing-0 << HTTP/1.1 500 Internal Server Error*
*DEBUG - http-outgoing-0 << Access-Control-Allow-Origin: **
*DEBUG - http-outgoing-0 << Access-Control-Allow-Headers: origin,
content-type, accept, authorization*
*DEBUG - http-outgoing-0 << Access-Control-Allow-Credentials: true*
*DEBUG - http-outgoing-0 << Access-Control-Allow-Methods: GET, POST, PUT,
DELETE, OPTIONS, HEAD*
*DEBUG - http-outgoing-0 << Content-Type: text/plain*
*DEBUG - http-outgoing-0 << Date: Thu, 14 Sep 2017 15:20:01 GMT*
*DEBUG - http-outgoing-0 << Connection: close*
*DEBUG - http-outgoing-0 << Content-Length: 98*
*INFO - status:Internal Server Error*
*INFO - Unable to create Enrichment Map:Internal Server
ErrorResponseEntityProxy{[Content-Type: text/plain,Content-Length:
98,Chunked: false]}*
*DEBUG - Connection manager is shutting down*
*DEBUG - http-outgoing-0: Close connection*
*DEBUG - Connection manager shut down*

**Comment by risserlin** [comment]
For some reason it is registering your EM version as -1.  Do you have the latest version (released last week) installed?  (also check to see if you have multiple EM version installed.  That can also cause issues) 
Can you open a web browser and paste this into the url bar: "http://localhost:1234/v1/commands/enrichmentmap/gseabuild" - what does it return?

**Comment by risserlin** [comment]
In the web browser it should say this:

<img width="527" alt="screen shot 2017-09-14 at 11 42 04 am" src="https://user-images.githubusercontent.com/3842763/30439470-db47adb6-9941-11e7-8c13-0ef0e176cc72.png">

**Comment by jgarces02** [comment]
I don't understand, because I've installed it today, so it's the latest
version (and I don't have other versions).

I can't open the url, I'm behind my university's proxy and it denies the
access... but in Cytoscape I was able to change the proxy settings and it was
working (apparently) good.

Thanks again!

**Comment by shaunpatel** [comment]
I am having the same issue. My web browser output returns the expected results. Could this somehow be related to the use of a CHIP file? Trying random things, when I used another database (that didn't require CHIP), I didn't have this issue and the visualization was successfully created. Any advice would be appreciated.

**Comment by ernstki** [comment]
@jgarces02, and for the benefit of anyone else who ended up here after googling for

    Unable to create Enrichment Map:Internal Server ErrorResponseEntityProxy{[Content-Type: text/plain,Content-Length: 98,Chunked: false]}*

I think you had the problem mentioned in #358. You probably needed to increase your p-value and FDR Q-value cutoffs, because they were too stringent for the dataset you were trying to analyze.
