### ISSUE TITLE
incompatibility of node and edge colours

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#336]
coloured em by dataset with 4 datasets. 
one of the colours of the nodes almost matches the edges such that when you export the image the nodes and edges seem to mesh into one. 
![screen shot 2018-05-07 at 4 10 46 pm](https://user-images.githubusercontent.com/3842763/39722629-67b3d35a-5211-11e8-8ec9-18c172d687a4.png)

**Comment by chrtannus** [comment]
But that's normal. It happens because both Edges and Charts got their colours from the datasets.
So initially edges are coloured with the dataset colours, right? Then, if you choose "Color by Data Set", now the node charts also get the same colours. That disconnected component has only one dataset, so its edges and charts have the same colour.

I cannot change the edge or chart colours in this case, otherwise users won't be able to identify the datasets by colour, the colour scheme would be confusing, inconsistent.

I could increase the node border width or change the node border colour, but I don't know if either will look good depending on the network zoom, node size, etc.

Can I have the session file for the attached screen shot? I'd like to test some alternatives with this particular example first.
