### ISSUE TITLE
Enrichment map error: "Failed: None of the gene sets have passed the filter"

### ISSUE THREAD

**Issue by giuseppedelnapalle** [BaderLab/EnrichmentMapApp#358]
Hi all,

I am looking for help to fix the problem of failing to build enrichment map. I tried to do it after doing GSEA, but I got the error shown below.

> Unable to create Enrichment Map:Internal Server ErrorResponseEntityProxy

There's no error throughout GSEA, and I built the enrichment map successfully with the example files from this tutorial. So the problem was likely to be caused by the input files. Additionally, error could not be avoided either using Cytoscape 3.6.1 or 3.7.0. The issue was initially posted at [GSEA help forum](https://groups.google.com/forum/#!topic/gsea-help/2lC3_3O4QCY), so please follow the link for more details.
 
Software information:
OS: Windows 10
GSEA: 3.0 (build 0160)
Cytoscape: 3.7.0
Java: 1.8.0_191

Thanks!

**Comment by risserlin** [comment]
I think that the issue relates to the title of the bug "none of the gene sets have passed filter".  Change the p-value and FDR threshold to something really lax like p.value --> 1.0 and FDR --> 0.5 and re-try creating the network.  Do you get the same issue?
![screen shot 2018-12-13 at 10 43 03 am](https://user-images.githubusercontent.com/3842763/49949583-f490ac80-fec3-11e8-9379-4b9ea667160b.png)

**Comment by giuseppedelnapalle** [comment]
Thanks, you are right. The parameters I used as recommended (_p_-value<0.05 & FDR <0.25) were too stringent for my data.

**Comment by ernstki** [comment]
![gsea_cytoscape_error_message+shadow](https://user-images.githubusercontent.com/4009681/57034563-dbdc2580-6c1d-11e9-897f-c6008677193c.png)

@mikekucera This is an extremely user-unfriendly way of saying "None of the gene sets have passed the filter. Try relaxing the gene set filter parameters." You only discover that's the _actual_ problem if you manage to figure out how to look at the GSEA application log.

Is this a GSEA bug, or an EnrichmentMap bug, or a Cytoscape bug? Someone needs to throw the poor user a bone here, because this issue comes up [again](https://groups.google.com/forum/#!topic/gsea-help/c8HiSHA6xR4) [and](https://groups.google.com/forum/#!topic/gsea-help/c8HiSHA6xR4) [again](https://groups.google.com/forum/#!topic/gsea-help/zpHwlAu0Jt8) in Internet forums.

**Comment by mikekucera** [comment]
Looks like a problem in GSEA desktop. Its not properly displaying the error message returned by EnrichmentMap.

**Comment by ernstki** [comment]
@mikekucera Wicked. Thanks for opening a pull request for it. `:)`
