### ISSUE TITLE
Unable to create Enrichment Map:Internal Server ErrorResponseEntityProxy{[Content-Type: text/plain,Content-Length: 165,Chunked: false]}

### ISSUE THREAD

**Issue by faizkhan1** [BaderLab/EnrichmentMapApp#372]
First of all, thank you very much for such a nice tool.

1.    I performed pathway enrichment analysis using GSEA and tried to visualized the results using Enrichmentmap but could not succeed. I attached the screenshot of the error.
2.    I tried to use Enrichmentmap plugin in Cytoscape but could not figure out which files should I used through I spent a lot of time on the user guide.  For example, files *Enrichment Pos/Neg: what are these and how these files should look like, it should contain genes and enrichment score?
3.    It will be nice if you provide a tutorial on a working example with all the required files used for Cytoscape.

Looking forward to your reply.
![Enrichmentmap_connection_error4](https://user-images.githubusercontent.com/28927461/58093330-91234d00-7bce-11e9-94d0-60bc1bfd4149.png)

**Comment by risserlin** [comment]
_1. I performed pathway enrichment analysis using GSEA and tried to visualized the results using Enrichmentmap but could not succeed. I attached the screenshot of the error._
it is hard to tell what the issue is from your screenshots.  Did you try and press the build button multiple times?  Sometimes when there are multiple versions of cytoscape installed there can be issues.  see the following bug report for details (https://github.com/BaderLab/EnrichmentMapApp/issues/357)
 
_2. I tried to use Enrichmentmap plugin in Cytoscape but could not figure out which files should I used through I spent a lot of time on the user guide.  For example, files *Enrichment Pos/Neg: what are these and how these files should look like, it should contain genes and enrichment score?_ 
We have detailed step by step instructions in our recent Nature protocols: https://www.nature.com/articles/s41596-018-0103-9 (a pdf is available on our publications page if you don't have access (http://baderlab.org/Publications)

_3. It will be nice if you provide a tutorial on a working example with all the required files used for Cytoscape._
All required files for the tutorial are available as supplementary material and they are also available here https://baderlab.github.io/Cytoscape_workflows/EnrichmentMapPipeline/index.html

**Comment by mikekucera** [comment]
There is a bug in GSEA where it does not show the error message from EnrichmentMap and shows a cryptic error message instead. If you open the GSEA application log (using the plus [+] button at the bottom left of GSEA window) you might be able to find the actual error message from EnrichmentMap. Often the problem is that the p-value and q-value cutoffs need to be relaxed.
