### ISSUE TITLE
take enrichment results from genemania or string and create EM results

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#377]
one click from genemania or string to see the enrichment results as EM.

**Comment by risserlin** [comment]
Got another request for this feature (String) from  Mohamed Farhat (University of Michigan)

**Comment by mikekucera** [comment]
Creating an EM network from String is straightforward, we even have a command that can do it, I just need to surface this functionality in the UI and add it to the docs. 

But how would this work for genemania?

**Comment by risserlin** [comment]
we just need the genemania results as a generic file.

<img width="866" alt="Screen Shot 2020-02-07 at 11 34 55 AM" src="https://user-images.githubusercontent.com/3842763/74047220-fd80ef00-499d-11ea-9ec5-f1a42ca2d44e.png">

**Comment by mikekucera** [comment]
The user provides the gmt file?

**Comment by risserlin** [comment]
You don't need a gmt file if the generic file has the last column being a list of genes.  They aren't listed in the genemania interface but they have to be there somewhere.

**Comment by mikekucera** [comment]
Silly question. The STRING app has a column called "FDR value", I'm pretty sure this column used to be called "FDR p-value" in an older version of the app. Is this column a p-value or a q-value?? I'm guessing they renamed the column because its a q-value and it was named wrong, but I don't know for sure.
