### ISSUE TITLE
Generic/gprofiler demanding a GMT file and crashing if one is provided

### ISSUE THREAD

**Issue by ghost** [BaderLab/EnrichmentMapApp#388]
I downloaded the cytoscape app. my file is a .txt and is formatted as shown
<img width="402" alt="Screenshot 2020-01-16 at 13 39 49" src="https://user-images.githubusercontent.com/59964630/72529852-05011c80-3866-11ea-868c-818704aaa003.png">

when I run this in the generic/gprofiler section (it is saved as a tab delimited txt file) this happens.

<img width="562" alt="Screenshot 2020-01-16 at 13 34 45" src="https://user-images.githubusercontent.com/59964630/72529907-23671800-3866-11ea-874f-8ff4f7606502.png">

when I delete the offending gene this happens

<img width="562" alt="Screenshot 2020-01-16 at 13 35 42" src="https://user-images.githubusercontent.com/59964630/72529930-2feb7080-3866-11ea-97a6-2f0ad7b63f80.png">

**Comment by ghost** [comment]
If I manually create a gmt file with every gene in its own section I get this 
<img width="480" alt="Screenshot 2020-01-16 at 14 20 51" src="https://user-images.githubusercontent.com/59964630/72532502-72fc1280-386b-11ea-8a2c-425bff0e79ec.png">

This is hardly a solution, is it possible to fix this or is it simply not possible to use EnrichmentMap on generic enrichment data

**Comment by risserlin** [comment]
In order to run EM without a gmt file you need to have an additional column with the genes that are associated with each geneset/pathway.  

see here for details - https://enrichmentmap.readthedocs.io/en/latest/FileFormats.html#generic-results-files

When you create your gmt file did you have a tab delimited list of all the genes in each pathway listed?  the screenshot of your resulting network shows that EM is not able to find any overlaps between the genesets which could be because there are no overlap (for example for threshold are set too high) or because there are no genes associated with each geneset. 

Can you send me the gmt file that you created so I can see what the issue is?  Or alternately, like above just paste an example 2 lines from it. 

Thanks,

**Comment by ghost** [comment]
this is information from a novel organism, all we have is the gene sequences, and their enrichment in two different media, the genes functions and pathways are not known.

Here is the gmt screenshot

<img width="283" alt="Screenshot 2020-01-16 at 14 51 39" src="https://user-images.githubusercontent.com/59964630/72535034-beb0bb00-386f-11ea-9265-0d52e6f4d3ca.png">

**Comment by risserlin** [comment]
that isn't a gmt file.  That looks like a list of your genes or something.  
You need to convert it into a gmt file.

The format for a gmt file is:
geneset name (tab) geneset description (tab) gene1 (tab) gene2 (tab) .....

**Comment by ghost** [comment]
ah ok, and seeing as this is a novel organism where the genesets are not known, then EM can do nothing. I will have to return and try again once we have generated genesets which can be trusted. Thanks for your time
