### ISSUE TITLE
Redundant edges in generic enrichment analysis enrichment map

### ISSUE THREAD

**Issue by funnell** [BaderLab/EnrichmentMapApp#40]
Hello,

I'm creating an enrichment map using generic enrichment analysis results. I'm inputting three files: GOBP  geneset GMT, and two enrichment result text files. I'm seeing two edges (green and blue) between each fully coloured node. I understand that each colour maps to a different dataset, but if I understand correctly the gene overlaps for geneset A and geneset B will be the same for both datasets since I'm using only one GMT file and generic result files. Also, the enrichment of a geneset in a dataset is represented by the colouring of the core and outer circles of the nodes so the extra edges and the edge colours themselves seem to be unnecessary. 
Is there a way for me to not have dataset specific edges?

Cytoscape 3.2.0 beta1
EnrichmentMap 2.0.2

**Comment by risserlin** [comment]
Hi, 
any chance you have an expression file that you used for both of the analyses?  What is happening in the above example is based on the enrichment EM is calculating the genes for each dataset.  For example if you have Geneset A(with genes 1, 2, 3, 4) and B (with gene 4,5,6,7) enriched in dataset 1 and geneset B(with gene 4,5,6,7) and C(with genes 6,7,8,9) enriched in dataset2  EM is calculating the dataset 1 to contain genes 1,2,3,4,5,6,7 and dataset 2 to contain genes 4,5,6,7,8,9.  When it does a direct comparison dataset 1 and dataset 2 have different genes eventhough they were potentially done on the same set of genes just geneset A wasn't enriched in dataset2 and geneset C wasn't enriched in dataset 1.

To get around this issue instead of having EM calculate the genes in each datatset you can supply an expression file for each dataset with the exact same set of genes.  You can use fake expression values if you don't have real ones.   

Ruth

**Comment by funnell** [comment]
So are edges meant to represent overlap between genesets only considering the genes of interest (e.g. differentially expressed genes)? I had been assuming the edges were meant to be overlap between genesets considering all annotated genes in the genesets.

**Comment by risserlin** [comment]
Yes, edges are meant to represent overlap between genesets only considering the "Analysis set".  In thresholded enrichment analysis (like David, bingo, gprofiler)  the analysis set often is the set of significant genes.  In a non-thresholded analysis like GSEA the analysis set could be all the genes on a microarray chip or all the proteins identified in a mass spec analysis.

**Comment by funnell** [comment]
Thanks. I think the user guide update addresses this.
