### ISSUE TITLE
gProfiler new version support

### ISSUE THREAD

**Issue by fbrundu** [BaderLab/EnrichmentMapApp#409]
I am trying to visualize gProfiler results through EnrichmentMap.
However, I noticed that the App is configured to work with a previous version of gProfiler, and I wasn't able to reformat the gProfiler results in order to visualize them with the App. Is there a way to use the new gProfiler with the App? On the other hand, it's probably not possible anymore to use the older gProfiler version.

**Comment by risserlin** [comment]
gprofiler interface was updated since the publication of our protocol but it still works with EM. What issue are you having the generic EM file generated through g:profiler?
(You can also access older version of g:profiler here but I would not recommend that - https://biit.cs.ut.ee/gprofiler_archive2/r1760_e93_eg40/web/)

**Comment by fbrundu** [comment]
Thanks, my bad. I thought that I had to download the file using the CSV button, not the GEM button. Now it works, thanks.
