### ISSUE TITLE
EM's heatmap table Description column doesnt reflect GSEA genesets

### ISSUE THREAD

**Issue by klai001** [BaderLab/EnrichmentMapApp#411]
Hi EM Team,
thanks for developing EM!
I have used GSEA-preranked results as my inputs of EM, both the network and heatmap turned out okay
the only caveat is that my heatmap's description does not reflect the genesets but rather numbers which it's unclear to me where it came from.
![EM](https://user-images.githubusercontent.com/55043905/81492440-3a74be80-92ca-11ea-9154-14488336295e.png)
Would appreciate some advice and suggestions on how to resolve it.
Many thanks!

**Comment by risserlin** [comment]
The expression file that EM is expecting has gene name in the first colum and gene description in the second column followed by any number of expression values(https://enrichmentmap.readthedocs.io/en/latest/FileFormats.html#txt).  From your screen shot it looks like the second column of your expression file contains expression values (but I am just guessing).  If you only have gene names and no descriptions then just open your expression file  and add a blank column between name and the expression values (or simply copy the name into the second column) before loading it into EM.  If you send me the first few lines of your expression file I can check it out to see what the issue is.

**Comment by klai001** [comment]
Hi Ruth 
thanks for your reply!
I managed to resolved it and it was a file format error
my columns were originally (with/ representing sep="\t") 
genes/expsample1/expsample2 etc.
but the gsea inputs require an additional column with description
genes/na for description(if there's no description)/expsample1/expsample2

i was wondering if it's possible for EM to reflect the GSEA genesets in which the genes belong to under the description column of the heatmap, and not just the description of the genes which is given by the user.

**Comment by risserlin** [comment]
unfortunately an individual gene can belong to many many genesets and the this list would get very long (and difficult to read) if we put it in description column of the heatmap.

If you would like to see all the genesets that a gene belongs to then the easiest way to do it is to put the gene name into the search bar in the top right hand corner of the cytoscape interface.  This will then select all nodes (genesets) where this gene is found.  If you you then navigate to the Node table in the table panel you can see the list of all the genesets where that gene is found.
