### ISSUE TITLE
Unable to create Enrichment Map: Internal Server Error Failed: null

### ISSUE THREAD

**Issue by LucoLab** [BaderLab/EnrichmentMapApp#415]
Hi,

I'm working on ubuntu 18.04, java 11 was freshly installed.
I have cytoscape 3.8 with enrichment map plugin install and open.
I use GSEA 4.0.3 to do en enrichment map but the soft doesn't want to open cytoscape.

```
25926    [INFO  ] - successfully connected to cytoscape rest
25934    [INFO  ] - Found enrichment map command
26129    [INFO  ] - Get URL:http://localhost:1234/v1/commands/enrichmentmap/gseabuild?edbdir=%2Fhome%2Fjp%2FDesktop%2FCovid19%2FGSEA%2FPATIENTS%2F237246_CUSTOM%2F237246%2Fedb&pvalue=0.005&qvalue=0.1&overlap=0.5&similaritymetric=OVERLAP&combinedconstant=0.5
26168    [INFO  ] - status:Internal Server Error
26170    [INFO  ] - Unable to create Enrichment Map: Internal Server Error
Failed: null
```
My GSEA result folder is downloaded from genepattern (v 20.0.x ) using GSEA Version: 4.0.3

Any idea ? Thanks.

**Comment by risserlin** [comment]
Are you trying to create your enrichment map from within gene pattern or from a GSEA app that is installed on your computer?

**Comment by LucoLab** [comment]
From GSEA that is installed on my computer.

**Comment by risserlin** [comment]
Unfortunately that error message is not informative.  It might be that it can't find one of the files that you are specifying.  
In GSEA click on the "+" in the bottom left hand of the main panel and it should give you some more descriptions about the error.  With the Cytoscape, enrichment map link it creates an URL in order to send the info to cytoscape.  There should be a line that starts:
"Get URL:http://localhost:1234/v1....."
If you cut and copy the whole line after the Get URL: and paste it into a web browser you should get a more meaningful error as to what is happening.
Alternately, you can just open cytoscape and enrichment map and load your GSEA results directly as described here - https://pubmed.ncbi.nlm.nih.gov/30664679/
