### ISSUE TITLE
Show in Pathway Commons is not working

### ISSUE THREAD

**Issue by s2hui** [BaderLab/EnrichmentMapApp#427]
Installed latest Cytoscape 3.8.0, built an EM (with the version that came installed with it) using GSEA results.
Selected a pathway and went to the heat map tab.
Right clicked on the pathway.  Apps -> Enrichment Map - Show in Pathway Commons is greyed out.
When I go to the heat map tab and click on the 3 horizontal bars, I am able to see the Show in Pathway Commons... feature.
When I click on that, it takes me to the pathway commons website but appears to hang or take a very long time- the screen is blank.
![Screen Shot 2020-09-16 at 9 58 21 AM](https://user-images.githubusercontent.com/10944134/93347879-9369db80-f803-11ea-9a5e-026a30ad06c0.png)
![Screen Shot 2020-09-16 at 9 56 04 AM](https://user-images.githubusercontent.com/10944134/93347898-98c72600-f803-11ea-97c4-68079958b995.png)

**Comment by mikekucera** [comment]
I think the pathway commons painter app isn't being maintained anymore. We should probably just remove that menu option.

**Comment by risserlin** [comment]
are there no plans to resuscitate it?

**Comment by gbader** [comment]
Hi. We never decided to decommission painter. I think we should keep it.
Are people using it?

Gary

**Comment by mikekucera** [comment]
I'm not sure if people are using it. Whoever has access to the server would have to check the logs.

I have noticed performance problems and sometimes hangs with the painter app in the past. I just tested it now and it seems to be working fine for me. I was able to open a gene list of length ~500 genes. But I have seen it hang on occasion.

**Comment by risserlin** [comment]
why is the option gray-ed out from EM interface though?  How can I test the server not from EM?

**Comment by mikekucera** [comment]
The pathway commons painter app requires expression and class data. If the genes in the gene set don't have expressions then the menu option is disabled.

Or it could be a bug :)

**Comment by risserlin** [comment]
EM is currently redirecting to:
https://beta.pathwaycommons.org/paint?uri=http%3A%2F%2Flocalhost%3A1234%2Fenrichmentmap%2Fexpressions%2F52%2F299&q=Interferon+alpha+beta+signaling

Is the painter app only available in beta version?

If the painter app is not maintained right now could we change the links to query pathway commons instead or as well?

**Comment by gbader** [comment]
Paint is at https://apps.pathwaycommons.org/paint - where did you find the beta link?

**Comment by risserlin** [comment]
That is the link that EM in cytoscape goes to.

**Comment by mikekucera** [comment]
I just tried it from the heatmap and from the context menu and in both cases it took me to https://apps.pathwaycommons.org/paint

I also did a text search on the EM source code and the word 'beta' does not appear.

If its redirecting to 'beta...' it must be happening on the server side.

**Comment by risserlin** [comment]
This is the link that I get redirected from in EM 3.3.1 from the heatmap menu -> search in pathways commons (because when I tried from the right click context menu the search pathway commons was grayed out.)
 https://beta.pathwaycommons.org/paint?uri=http%3A%2F%2Flocalhost%3A1234%2Fenrichmentmap%2Fexpressions%2Fheatmap&q=EnrichmentMap

When I sub https://apps.pathwaycommons.org/paint for the front part I get an empty page but not sure if that is a problem on my side.  oh wait ... I can't just sub it because it won't have the expression data.

**Comment by risserlin** [comment]
Turns out there is a property that I had set to beta.pathwaycommons.org/paint.  Not sure when or where that property was set but when I updated cytoscape properties for org.baderlab.erichmentmap for property pathway.commons.url to point to the main site instead of beta.  
(It goes to the right site but has no results but that is a different issue that I will report separately.  If the EM has not expression data then it just launches an empty web browser, no errors)
