### ISSUE TITLE
Latest version of GSEA (4.1.0) on Windows sets some of the p-values and FDR values to "---"

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#432]
causes EM to return with an error:

 Building EnrichmentMap – Parsing Bingo Enrichment Result File – For input string “---“

Also, gsea output files are no longer xls but are now tsv.  Not sure if that is an issue with the automatic file detection.  It didn't work for me but I was running GSEA on windwos and copying the files over to mac so it might have been related to that.  

Originally reported to me by Georgia Mitsa 

I have example GSEA results to test issue but here is an example:
NAME	GS<br> follow link to MSigDB	GS DETAILS	SIZE	ES	NES	NOM p-val	FDR q-val	FWER p-val	RANK AT MAX	LEADING EDGE	
RESPIRATORY ELECTRON TRANSPORT%REACTOME DATABASE ID RELEASE 74%611105	RESPIRATORY ELECTRON TRANSPORT%REACTOME DATABASE ID RELEASE 74%611105	Details ...	34	-0.19492649	---	---	1.0	0.0	1332	tags=97%, list=73%, signal=353%	
ENERGY DERIVATION BY OXIDATION OF ORGANIC COMPOUNDS%GOBP%GO:0015980	ENERGY DERIVATION BY OXIDATION OF ORGANIC COMPOUNDS%GOBP%GO:0015980	Details ...	51	-0.16224304	---	---	1.0	0.0	1442	tags=98%, list=79%, signal=455%	
CITRATE METABOLIC PROCESS%GOBP%GO:0006101	CITRATE METABOLIC PROCESS%GOBP%GO:0006101	Details ...	15	-0.49585405	-1.9621902	0.0	0.008359932	0.005	928	tags=100%, list=51%, signal=202%

**Comment by jtoy7** [comment]
I am having the same issue running Cytoscape on Ubuntu. I ran a similar analysis using the same versions of GSEA and Cytoscape a few weeks ago without issue, but now I get the same error:

Building EnrichmentMap – Parsing Bingo Enrichment Result File – For input string “---“

I tried updating from Cytoscape v3.8.1 to v3.8.2, but get the same error.

**Comment by risserlin** [comment]
It will need to fixed in the EM app but in the meantime if you open up your na_pos and na_neg results files and replace the "---" values with 1 and then re-run with the updated files it should work for now.

**Comment by jtoy7** [comment]
So is that what's happening - "---" is showing up instead of "1"? That is interesting because there are only four instances of "---" in one of my results files, and they are in the two column in the last two rows, which have other entries that actually show "1". Why would some "1" values show up, but others show up as "---"?

**Comment by risserlin** [comment]
From the file that was sent to me, the "---" show up in the NES column and Nominal p-value column.  the FDR q-value is set to 1 and the FWER is set to zero.  There are other records in the table that have FDR q-values of 1 but I think that what makes these records different is the FWER is 0.  Originally I assumed that it was related to ES values being too small but my two records don't have the lowest ES scores.  This is looking more like a bug in the latest version of GSEA and less like it was by design.  -- I have posted a message on the gsea-help (they recommend posting bugs there.  ) https://groups.google.com/g/gsea-help/c/0OjisuAu2qo

**Comment by ACastanza** [comment]
@jtoy7 Could you please reach out to us at gsea-team@broadinstitute.org? 
The "---" you're seeing in the results is typically caused by a problem with the underlying dataset, such as when the distribution of the gene ranking is extremely skewed towards one phenotype. When this happens, GSEA can fail to generate valid enrichment scores for the permutations resulting in a failed normalization for that gene set.
Depending on what the dataset looks like, simply omitting those sets downstream might be just fine (this is what setting the "---"=1 should do), but it might be best if we actually take a closer look at the data that is causing the problem since this is a fairly complicated error that involves the distribution of the input data, the specific members of the gene set being tested, and the random number seed that is used to initialize the permutation algorithm. Any data you send to the gsea-team address will be kept strictly confidential.

@risserlin In our testing EnrichmentMap was able to parse the tsv, I know we tested that on MacOS, but I can't remember if we also checked Windows systems. Also, feel free to direct any other users who reach out to you folks with the "---" issue our way.

-Anthony

Anthony S. Castanza, PhD
Curator, Molecular Signatures Database
Mesirov Lab, Department of Medicine
University of California, San Diego
http://gsea-msigdb.org/

**Comment by risserlin** [comment]
The initial bug I received was specific to windows 10 and I was able to recreate it but then the latest report we received was  for ubuntu.

**Comment by mikekucera** [comment]
Hi @risserlin, do you still have the example GSEA results files that trigger this issue? If you do can you please send them to me. Thanks.

**Comment by risserlin** [comment]
@mikekucera I emailed you some example files and GSEA results folder.

**Comment by mikekucera** [comment]
Thanks!

**Comment by mikekucera** [comment]
Is it safe to just use the value 1 when "---" is encountered. Do we need to warn the user when this happens?

**Comment by risserlin** [comment]
I think it would be a good idea to issue a warning that their GSEA results contain unusual results and maybe puts a link to GSEA help desk for more info.
