### ISSUE TITLE
No longer able to create an enrichment map with just a gmt file

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#473]
Not sure when this functionality disappeared but if you just specify a gmt file a enrichment should be built but it now comes up with an error saying missing an enrichment file. 
If you get rid of the dataset and just specify the gmt file the build button is disabled.

**Comment by mikekucera** [comment]
Hi Ruth, I just tested this with EnrichmentMap 3.3.3 and a baderlab GMT file and it works. I was able to create an enrichment map network with just the GMT file. 

Perhaps the issue is specific to C2 pathways from Msigdb?

Can you please send me the file you were using when you ran into this error?

Thanks.

**Comment by risserlin** [comment]
HI Mike, 
You are right.  It does work.  I think that I tried to create it by specifying just gmt file in the common files section.  If you add a dataset and add the gmt to the dataset it works. 
Thanks, 
Ruth
