### ISSUE TITLE
Issue using enrichment map columns in Cytoscape formula builder

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#492]
Issue received through email from Laura Lewandowski - 

I am running into an issue in trying to use a formula in an added column in enrichment Map.
I am trying to take the -log of the pvalue, but when I enter log (enrichment map::pvalue) I get the following error:
The training videos or github documentation do not address this.
<img width="1311" alt="image001" src="https://user-images.githubusercontent.com/3842763/185416336-2f0d9562-4487-46c3-acf6-5d7e6bf7e28f.png">

Verified issue was EM columns.  Created a fake column with fake p-values called my_pval and was able to create a formula using that column and -log function.  

Maybe is there a way to escape the EM column name to get it to work?

**Comment by risserlin** [comment]
Work around - you can rename the EM column name and even though it gives you an error it renames the column and will work with functions after that.

Error when you rename the column - 

![Screen Shot 2022-08-18 at 10 15 07 AM](https://user-images.githubusercontent.com/3842763/185417203-7ade7aa2-da4a-4e8f-b91e-af0fe976419b.png)

**Comment by Lauralew11** [comment]
Hello! I am the person who submitted this bug report. This work around works beautifully- thank you so much for the help!

**Comment by mikekucera** [comment]
The problem is the parenthesis in the column name. You will have to escape them in the formula editor using backslashes, like this... `${EnrichmentMap::pvalue \(8_1_22_KH_metascape\)}`

I will open a bug on Cytoscape for this, either the parenthesis should be accepted as they are, or the formula builder should automatically insert the backslashes when inserting the column name.
