### ISSUE TITLE
testing EM 3.3.5: hiding one dataset reset the style.

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#503]
When working with a master map,  I usually start by adjusting the style (e.g gene-sets style). It is very frequent that I want to visualize just one of the dataset on this formatted map but it resets the style. I know that I can copy the style but even if I know it, I forget to do it and users won't know about it anyway.
I know that it might be a Cytoscape feature more than EM and that we discussed it frequently but it is an enhancement that would be nice to have. I don't know if there is a way to at least have a pop up dialog box with a warning or a pop up dialog that will make us save our style each time it is about to be reset. Just a thought.

Adjusting the style:
![Screen Shot 2022-12-02 at 11 15 25 AM](https://user-images.githubusercontent.com/7570379/205339178-f152221a-1a2b-4711-8f5a-a0c1cd6d9da0.png)

Style reset after I remove one dataset:
![Screen Shot 2022-12-02 at 11 15 37 AM](https://user-images.githubusercontent.com/7570379/205339787-5a60f7e8-cdbe-449a-86a3-154148efa5c0.png)

**Comment by mikekucera** [comment]
Hi Veronique,

When changing the visible datasets it only resets part of the style...
- edge paint (necessary when changing data set colors)
- node charts (necessary because the data set chart pie slices need to change)
- node shapes (NOT necessary)
- node size (NOT necessary)
- node colors (NOT necessary, but also not really visible because the charts overlap the node)

I'm going to change it so that node shape/size/color no longer gets reset. Would that be adequate to mitigate this problem?

**Comment by veroniquevoisin** [comment]
Yes, it would work as I saw that you have added the extra edge color
option!
