### ISSUE TITLE
EM version 3.4.0-SNAPSHOT" Default style node color: -log10(pvalue)_max (enhancement)

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#538]
Thanks for adding this default node color style .
For GSEA or generic format with NES +1 and -1, is it  possible to add a column attribute that would look like: -log10(pvalue)_max * sign(NES) so that we get blue and red nodes?
![Screenshot 2024-02-26 at 2 40 02 PM](https://github.com/BaderLab/EnrichmentMapApp/assets/7570379/be0b18e2-5891-47f4-b3a6-68b4991e6782)

**Comment by veroniquevoisin** [comment]
Here is how I changed the style:
<img width="1238" alt="Screenshot 2024-02-28 at 9 43 00 AM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/7570379/6703d5d4-59bc-4180-a2aa-7dd5485caf7c">

**Comment by mikekucera** [comment]
Hi Veronique, I have a question...

The mapping for -log10(pvalue) in your screenshot uses the range (2.16, 2.92) which does not include zero and has size 2.92 - 2.16 = 0.76

If we make the range go from (-2.92, 2.92) then the range will include zero and have a size more than double the original size. This will affect the color interpolation because the gradient covers a much larger range. 

Is this ok? And should the range for -log10(pvalue) go from zero to the max value?

**Comment by veroniquevoisin** [comment]
Hi Mike,

This one would be ideal: 0 in the middle:If we make the range go from
(-2.92, 2.92) then the range will include zero and have a size more than
double the original size. This will affect the color interpolation because
the gradient covers a much larger range.

Veronique

**Comment by mikekucera** [comment]
For the regular -log10(pvalue) chart should it go from 0 to 2.92 in this case? I think that would be consistent. Switching to the -log10(pvalue)*sign(NES) chart wouldn't affect the color of nodes that have a positive NES, which makes sense to me.

**Comment by veroniquevoisin** [comment]
Yes, what you are saying makes sense to me.
Veronique

**Comment by mikekucera** [comment]
Hi Veronique, another question.

The mapping was to the `-log10(pvalue)_max` column, which contains the maximum -log10(pvalue) when there's more than one data set. 

With NES I think its a bit harder to deal with. Its possible the NES could be positive in one data set and negative in another. Its not clear to me what to do in this situation. 

Options...
1) Multiply by the sign of the largest NES value
2) Only multiply by sign(NES) when the network has exactly one data set, otherwise just use `-log10(pvalue)_max` for networks that have more than one data set.
3) others options?

**Comment by veroniquevoisin** [comment]
Hi Mike,
from your suggestions I would go with option2.
Veronique

**Comment by mikekucera** [comment]
7e87f18, 512dc4c00b21019153f00b01f899fbe541fd32f4, 00443a02ab69b0e40ea73627b2358958c07eff64, 1cd87e1b16661b53378220deccb81e1b27aeade1, ae4b9bc91cd043ba205113d9d5fefb5ececf9910
