### ISSUE TITLE
class file not working in latest EM

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#550]
using common expression file and common class file - seems to recognize that there are multiple classes (because collape by class is enabled) but there are no class colouring in the heatmap
<img width="671" alt="Screen Shot 2024-08-26 at 3 22 05 PM" src="https://github.com/user-attachments/assets/6e7d6fee-8c5c-4e9f-9ae6-e82be6022dd8">
all samples are blue
and when I collapse them I get this weirdness:
<img width="336" alt="Screen Shot 2024-08-26 at 3 22 48 PM" src="https://github.com/user-attachments/assets/67f0e3d9-5115-4ef3-a047-5b3b3e4d39ad">
the five classes are listed but there is this weird na_pos and na_neg column that I don't know where it is from

Using EM 3.4
AA 1.5.1.snapshot

**Comment by mikekucera** [comment]
Hi Ruth, can you please send me the data files for this example.

**Comment by mikekucera** [comment]
Nevermind I am able to reproduce it myself.

**Comment by mikekucera** [comment]
So what's happening is its combining the classes from the class file with the ones in the dialog here...

<img width="887" alt="Screenshot 2024-08-28 at 12 33 35 PM" src="https://github.com/user-attachments/assets/30108b8d-740e-4eef-a59d-c44bdbf4e948">

Unfortunately clearing out those fields so they are blank doesn't fix it. The extra phenotypes just default to "UP" and "DOWN" instead of "na_pos" and "na_neg".

What should we do in this situation? We could add validation that stops the user from creating the network if the values in the Phenotype fields don't match the class file. But I think this would be very annoying, since the defaults will likely never match.

EDIT: The phenotypes are used in the heat map panel to highlight the two cases that are being compared in the experiment. That is likely very useful.

@risserlin What do you think?

**Comment by mikekucera** [comment]
How about this...
If the Phenotypes from the dialog don't match the class file, then ignore them, just show the phenotypes from the class file in the heat map. If they do match then highlight them as usual.

I could also add a warning message to the "Common Files" page in the dialog telling the user that if they use a common class file that they should make sure the phenotypes in the data sets match what's in the file.

**Comment by risserlin** [comment]
so it is one level more complicated than that I think.  

Firstly the expression file was duplicated for each dataset even through there was a common file.  

I have five phenotypes and the rank files are created A vs all, B vs all, C vs all .... and I am looking at only the positive enrichments for each dataset.  So for each dataset under the phenotypes I only specified the na_pos.  (for dataset 1 I set it to A, for dataset 2 I set it to B ...) and I left the na_neg blank (I actively deleted what was there.).  For each dataset it actually worked and it highlighted just A in dataset A and just B in dataset B (with the addition of these na_pos and na_neg columns).  But the expression was repeated 5 times and highlighted region for each expression was specific to the phenotype.  Is there a way to do this suck that it is truly a common expression and a common class file (highlighting linked to which rank is selected) ?

**Comment by mikekucera** [comment]
In this case the positive phenotype to highlight depends on the data set. That's why it repeats the expressions again for each data set. Its not linked to the ranks I don't think, so selecting a different rank wouldn't work.

But that should be fixable. We could highlight the columns that are selected as pos or neg phenotypes in all data sets first, then list all the common ones afterward without repeating them.
