### ISSUE TITLE
Add ability to overwrite old post analysis visual style

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#69]
Instead of re-running EM can we have an option to delete the existing post analysis bypasses 
![screen shot 2015-04-20 at 1 41 41 pm](https://cloud.githubusercontent.com/assets/3842763/7236483/38a646c2-e763-11e4-9ca0-9ae7ae039a7b.png)

**Comment by mikekucera** [comment]
- Don't use -1 for edge color, use 4 instead
- Its ok for node color (and border color) to be bypass (solves confusing use of yellow in continuous mapping)
- Post-analysis should generate a new visual style (that is basically a clone of the EM visual style)
- Use a formula for edge width instead of doing the mapping in code (the user doesn't know where the mapped value came from). May need to create new edge attributes after the fact if they weren't created by EM.

**Comment by mikekucera** [comment]
This is basically done. Please open a new issue if you would like any changes.
