### ISSUE TITLE
Addition of rank sum library causes EM jar to be too big

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#7]
The Rank sum test incorporated library inflates the jar.  Look into calculating the rank sum without having to include the library.

**Comment by mikekucera** [comment]
I found a way to use Maven with a tool called Proguard to shrink the app jar file. Basically it analyzes the jar and removes any class files that are not being used, even from libraries. I ran it on the latest build with the colt and apache commons math libraries embedded. Without proguard the jar is 2,714k, with proguard it shrinks to 839k.

I like this approach because its just a few extra lines in the pom file, rather than copy-pasting code from apache commons into the project source.

Proguard comes with the Android Development Tools and is the standard way to shrink Android App jars. So its in pretty heavy use and we can assume its reliable.

Ruth, is it ok if I go in this direction?

**Comment by risserlin** [comment]
Perfect.  Thanks.
